apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: apiserver
  name: apiserver
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: apiserver
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: apiserver
    spec:
      containers:
      - image: {{ .Values.image.registry }}/{{ .Values.image.repository }}:{{ .Values.image.tag }}
        name: apiserver
        resources: {}
status: {}
