apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: apiserver
    app.kubernetes.io/managed-by: Helm
  name: apiserver
spec:
  ports:
  - port: {{ .Values.image.port }}
    protocol: TCP
    targetPort: {{ .Values.image.port }}
  selector:
    app: apiserver
status:
  loadBalancer: {}
